name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: iiasa/actions/.github/workflows/lint.yaml@migrate-message-ix-workflows
    with:
      max-complexity: 26
      # If the "Latest version testable on GitHub Actions" in pytest.yaml
      # is not the latest 3.x stable version, adjust here to match:
      python-version: "3.10"
      type-hint-packages: pytest genno GitPython xarray sphinx types-setuptools
