name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. Use 100 to be sure to include the latest
        # tag; this lets setuptools-scm determine the version number.
        fetch-depth: 100

    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: |
          $HOME/.cache/pip
          $HOME/Library/Caches/pip
          $HOME/appdata/local/pip/cache
        key: lint-${{ runner.os }}

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --max-complexity=29 --show-source --statistics

    - name: Test package build
      run: |
        pip install twine wheel
        python3 setup.py bdist_wheel sdist
        twine check dist/*

    - name: Test documentation build
      run: |
        pip install .[docs,tests,tutorial]
        make --directory=doc html
