name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GAMS_VERSION: 25.1.1

jobs:
  pytest:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        include:
        - os: macos-latest
          GAMS_OS: macosx
          marks: not performance
        - os: ubuntu-latest
          GAMS_OS: linux
          marks: not performance
        - os: windows-latest
          GAMS_OS: windows
          marks: not performance

      fail-fast: false

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: r-lib/actions/setup-r@master

    - name: Use OpenJDK 14 (macOS only)
      # Using the default OpenJDK 1.8 on the macos-latest runner produces
      # "Abort trap: 6" when JPype1 starts the JVM
      if: ${{ startsWith(matrix.os, 'macos') }}
      uses: actions/setup-java@v1
      with:
        java-version: '14'

    - name: Cache GAMS installer, Python and R packages
      uses: actions/cache@v2
      with:
        path: |
          gams
          $HOME/.cache/pip
          $HOME/Library/Caches/pip
          $HOME/appdata/local/pip/cache
          ${{ env.R_LIBS_USER }}
        key: ${{ matrix.os }}-${{ env.GAMS_VERSION }}
        restore-keys: ${{ matrix.os }}-

    - name: Install curl, GAMS, and Graphviz
      env:
        CI_OS: ${{ matrix.os }}
        GAMS_OS: ${{ matrix.GAMS_OS }}
      run: |
        ci/install-curl.sh
        ci/install-gams.sh
        ci/install-graphviz.sh
      shell: bash

    - name: Check GAMS
      run: gams
      shell: bash

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Install the Python package and dependencies
      run: pip install .[docs,tests,tutorial]

    - name: Install system R dependencies (Linux only)
      # This is faster than allowing remotes::install_deps() to do the
      # installation, below. However, not all packages are available in 18.04.
      # TODO install more of the Linux dependencies in this way to speed up.
      if: ${{ contains(matrix.os, 'ubuntu') }}
      run: sudo apt install -q libcurl4-openssl-dev r-cran-devtools

    - name: Set RETICULATE_PYTHON (Windows only)
      # Without this, reticulate tries to use Python 2.7 in the next step
      if: ${{ contains(matrix.os, 'windows') }}
      run: |
        Write-Host "::set-env name=RETICULATE_PYTHON::${{ env.PYTHONLOCATION }}\python.exe"

    - name: Install the R package and dependencies
      # To debug, add lines line:
      # print(reticulate::py_config())
      # reticulate::py_run_string("import os; print(os.environ)")
      run: |
        install.packages(c("devtools", "remotes", "IRkernel"))
        remotes::install_cran("rcmdcheck")
        remotes::install_deps("rixmp", dependencies = TRUE)

        # Set up R Jupyter kernel for tutorial notebooks
        IRkernel::installspec()

        # --no-multiarch avoids building arch=i386 on Windows, which is not
        # needed and causes errors
        devtools::install("rixmp", args = "--no-multiarch")
      shell: Rscript {0}

    - name: Run pytest
      run: pytest ixmp -m "${{ matrix.marks }}" --verbose --cov-report=xml

    # This standard R check can replace the tests in tests/test_r.py, but
    # requires improvements to the rixmp packaging.
    # - name: Run R CMD check
    #   run: |
    #     rcmdcheck::rcmdcheck("rixmp", args = c("--no-manual", "--as-cran"),
    #                          error_on = "warning", check_dir = "check")
    #   shell: Rscript {0}

    - name: Upload test coverage to Codecov.io
      uses: codecov/codecov-action@v1
